'use strict';
const adjectivesList = [
    [
        {
            h1: 'PRZYMIOTNIKI',
            table: {
                note1: 'ANGIELSKI',
                note2: '',
            },
            note: {},
        },
    ],
    [
        { group: 1, pl: 'niewielki / maleńki / malutki', en: 'tiny', note: 'tiny<u>s</u>' },
        { group: 1, pl: 'głośny', en: 'loud', note: '' },
        { group: 1, pl: 'inny / innym / kolejnym', en: 'another', note: '' },
        { group: 1, pl: 'trudny', en: 'difficult', note: '' },
        { group: 1, pl: 'twardy / trudny / ciężki', en: 'hard', note: '' },
        { group: 1, pl: 'łatwy / prosty', en: 'easy', note: '' },
        { group: 1, pl: 'prosty / nieskomplikowany', en: 'simple', note: '' },
        { group: 1, pl: 'podstawowy / zasadniczy', en: 'basic', note: '' },
        { group: 1, pl: 'wielki / ogromny', en: 'great', note: '' },
        { group: 1, pl: 'najnowszy / najświeższy / ostatni', en: 'latest', note: '' },
        { group: 1, pl: 'słaby / osłabiony', en: 'weak', note: '' },
        { group: 1, pl: 'przyjemny / sympatyczny / miły', en: 'pleasant', note: '' },
        { group: 1, pl: 'potrzebny / niezbędny / konieczy', en: 'necessary', note: '' },
        { group: 1, pl: 'straszny / okropny / paskudny', en: 'terrible', note: '' },
        { group: 1, pl: 'oktopny / wstrętny / obrzydliwy', en: 'awful', note: '' },
        { group: 1, pl: 'dostępny / osiągalny', en: 'available', note: '' },
        { group: 1, pl: 'zajęty / zapracowany', en: 'busy', note: '' },
        { group: 1, pl: 'gorszy', en: 'worse', note: '' },
        { group: 1, pl: 'interesujący', en: 'interesting', note: '' },
        { group: 1, pl: 'darmowy / wolny / bezpłatny', en: 'free', note: '' },
        { group: 1, pl: 'cudowny / wspaniały', en: 'wonderful', note: '' },
        { group: 1, pl: 'gotowy', en: 'ready', note: '' },
        { group: 1, pl: 'lepszy', en: 'better', note: '' },
        { group: 1, pl: 'ciężki', en: 'heavy', note: '' },
        { group: 1, pl: 'nudny', en: 'boring', note: '' },
        { group: 1, pl: 'idealny', en: 'ideal', note: '' },
        { group: 1, pl: 'wolny', en: 'slow', note: '' },
        { group: 1, pl: 'szybki', en: 'fast', note: '' },
        { group: 1, pl: 'nowy', en: 'new', note: '' },
        { group: 1, pl: 'dobry', en: 'good', note: '' },
        { group: 1, pl: 'wysoki', en: 'high', note: '' },
        { group: 1, pl: 'stary', en: 'old', note: '' },
        { group: 1, pl: 'duży / wielki', en: 'big', note: '' },
        { group: 1, pl: 'mały', en: 'small', note: '' },
        { group: 1, pl: 'różny', en: 'different', note: '' },
        { group: 1, pl: 'długi', en: 'long', note: '' },
        { group: 1, pl: 'mały', en: 'little', note: '' },
        { group: 1, pl: 'ważny', en: 'important', note: '' },
        { group: 1, pl: 'niedobry / zły', en: 'bad', note: '' },
        { group: 1, pl: 'rzeczywisty / realny', en: 'real', note: '' },
        { group: 1, pl: 'dobry', en: 'good', note: '' },
        { group: 1, pl: 'zdolny', en: 'able', note: '' },
        { group: 1, pl: 'późny / spóźniony', en: 'late', note: '' },
        { group: 1, pl: 'lepszy', en: 'better', note: '' },
        { group: 1, pl: 'cały', en: 'whole', note: '' },
        { group: 1, pl: 'użyteczny / pożyteczny / przydaty', en: 'useful / handy', note: '' },
        { group: 1, pl: 'inny / pozostały', en: 'other', note: '' },
        { group: 1, pl: 'perfekcyjny / doskonały', en: 'perfect', note: '' },
        { group: 1, pl: 'zimny', en: 'cold', note: '' },
        { group: 1, pl: 'pusty', en: 'empty', note: '' },
        { group: 1, pl: 'wypoczęty / wyspany', en: 'well-rested', note: '' },
        { group: 1, pl: 'obowiązkowe / obligatoryjny', en: 'mandatory', note: '' },
        { group: 1, pl: 'poryw / wiatru', en: 'gust', note: '' },
        { group: 1, pl: 'samotny', en: 'lonely', note: '' },
        { group: 1, pl: 'rozsądny / mądry', en: 'wise', note: '' },
        { group: 1, pl: 'obłożony', en: 'coated', note: '' },
        { group: 1, pl: 'ulubiony', en: 'favourite', note: '' },
        { group: 1, pl: 'chwytliwy  / wpadający w ucho', en: 'catchy', note: '' },
        { group: 1, pl: 'radosny / pogodny / wesoły', en: 'cheerful', note: '' },
        { group: 1, pl: 'przenośny / łatwy do przeniesienia', en: 'portable', note: '' },
        { group: 1, pl: 'tandetny / tani / kiczowaty', en: 'cheesy', note: '' },
        { group: 1, pl: 'zajebisty / rewelacyjny / odjechany / czadowy', en: 'dope', note: '' },
        { group: 1, pl: 'obecny / bieżący / aktualny', en: 'current', note: '' },
        { group: 1, pl: 'pesymistyczny', en: 'pessimistic', note: '' },
        { group: 1, pl: 'bystry / mądry', en: 'clever', note: '' },
        { group: 1, pl: 'leniwy', en: 'lazy', note: '' },
        { group: 1, pl: 'wysoki / wższy niż przeciętni', en: 'tall', note: '' },
        { group: 1, pl: 'równy / jednakowy / taki sam', en: 'equal', note: '' },
        { group: 1, pl: 'dziwny', en: 'strange', note: '' },
        { group: 1, pl: 'tani (cena)', en: 'cheap', note: '' },
        { group: 1, pl: 'podwójny', en: 'double', note: '' },
        { group: 1, pl: 'porównawczy', en: 'comparative', note: '' },
        { group: 1, pl: 'ciasny / obcisły (o ubraniu)', en: 'tight', note: '' },
        { group: 1, pl: 'rysowanie', en: 'drawing', note: '' },
        { group: 1, pl: 'głodny', en: 'hungry', note: '' },
        { group: 1, pl: 'przeciętny / średni', en: 'average', note: '' },
        { group: 1, pl: 'najlepiej sprzedający się', en: 'bestselling', note: '' },
        { group: 1, pl: 'obraźliwy / chamski / ordynarny', en: 'offensive', note: '' },
        { group: 1, pl: 'wciągający / trzymający w napięciu', en: 'engrossing', note: '' },
        { group: 1, pl: 'przywiązany (emocjonalnie)', en: 'attached', note: '' },
        { group: 1, pl: 'infantylny / dziecinny', en: 'childish', note: '' },
        { group: 1, pl: 'supernowoczesny', en: 'state-of-the-art', note: '' },
        { group: 1, pl: 'gorliwy / zapalony / namiętny / entuzjastyczny', en: 'avid', note: '' },
        { group: 1, pl: 'odpowiedni / stosowny / właściwy', en: 'appropriate', note: '' },
        { group: 1, pl: 'uprzejmy / grzeczny / kulturalny', en: 'polite', note: '' },
        { group: 1, pl: 'upadła (o reputacji)', en: 'fallen', note: '' },
        { group: 1, pl: 'mało prawdopodobny / nieprawdopodobny', en: 'unlikely', note: '' },
        { group: 1, pl: 'zadowolony (szczęśliwy z jakiegoś powodu)', en: 'glad', note: '' },
        { group: 1, pl: 'dumny', en: 'proud', note: '' },
        { group: 1, pl: 'podniecony / podekscytowany', en: 'excited', note: '' },
        { group: 1, pl: 'zasmucony / zmartwoiny / w złym homorze', en: 'upset', note: '' },
        { group: 1, pl: 'własny', en: 'own', note: '' },
        { group: 1, pl: 'brzydki / szpetny', en: 'ugly', note: '' },
        { group: 1, pl: 'gładki wygładzony', en: 'smooth', note: '' },
        { group: 1, pl: 'wąski', en: 'narrow', note: '' },
        { group: 1, pl: 'olbrzymi / ogromny', en: 'huge', note: '' },
        { group: 1, pl: 'pospolity / powszechny / zwykły', en: 'common', note: '' },
        { group: 1, pl: 'ładny', en: 'pretty', note: '' },
        { group: 1, pl: 'rzadki', en: 'rare', note: '' },
        { group: 1, pl: 'szorstki / chropowaty', en: 'rough', note: '' },
        { group: 1, pl: 'szeroki', en: 'wide', note: '' },
        { group: 1, pl: 'jasny / jaskrawy / lśniący', en: 'brilliant', note: '' },
        { group: 1, pl: 'fantastyczny / nieprawdopodobny', en: 'fantastic', note: '' },
        { group: 1, pl: 'taki sam / identyczny', en: 'same', note: '' },
        { group: 1, pl: 'głęboki', en: 'deep', note: '' },
        { group: 1, pl: 'prosty (biegnący prosto)', en: 'straight', note: '' },
        { group: 1, pl: 'cierpliwy', en: 'patient', note: '' },
        { group: 1, pl: 'dobrze', en: 'well', note: '' },
        { group: 1, pl: 'prawie / niemal / o mało / mało co', en: 'almost', note: '' },
        { group: 1, pl: 'porywający / wciągający (np.: film, książka)', en: 'gripping', note: '' },
        { group: 1, pl: 'nieciekawy / nudny / monotonny', en: 'dull', note: '' },
        { group: 1, pl: 'obudzony', en: 'awake', note: '' },
        { group: 1, pl: 'rozpoznawalny', en: 'recognisable', note: '' },
        { group: 1, pl: 'logiczny / spójny / koherentny', en: 'coherent', note: '' },
        { group: 1, pl: 'nieznany', en: 'unknown', note: '' },
        { group: 1, pl: 'suchy', en: 'dry', note: '' },
        { group: 1, pl: 'gorzki (o smaku)', en: 'bitter', note: '' },
        { group: 1, pl: 'bezpieczny', en: 'safe', note: '' },
        { group: 1, pl: 'ostry (np.: nóż, krawędź)', en: 'sharp', note: '' },
        { group: 1, pl: 'mokry / namoczony / wilgotny', en: 'wet', note: '' },
        { group: 1, pl: 'starożytny', en: 'ancient', note: '' },
        { group: 1, pl: 'biedny', en: 'poor', note: '' },
        { group: 1, pl: 'mięki', en: 'soft', note: '' },
        { group: 1, pl: 'sławny / słynny', en: 'famous', note: '' },
        { group: 1, pl: 'śmieszny / zabawny', en: 'funny', note: '' },
        { group: 1, pl: 'lśniący / świecący', en: 'shiny', note: '' },
        { group: 1, pl: 'chory', en: 'ill', note: '' },
        { group: 1, pl: 'hałasujący', en: 'noisy', note: '' },
        { group: 1, pl: 'smutny', en: 'sad', note: '' },
        { group: 1, pl: 'najwięcej / najbardziej', en: 'the most', note: '' },
        { group: 1, pl: 'brudny', en: 'dirty', note: '' },
        { group: 1, pl: 'wściekły / rozwścieczony', en: 'furious', note: '' },
        { group: 1, pl: 'bolesny / nieprzyjemny', en: 'painful', note: '' },
        { group: 1, pl: 'gadatliwy / rozmowny', en: 'talkative', note: '' },
        { group: 1, pl: 'płytki', en: 'shallow', note: '' },
        { group: 1, pl: 'egoistyczny / samolubny', en: 'selfish', note: '' },
        { group: 1, pl: 'niebiezpieczny', en: 'dangerous', note: '' },
        { group: 1, pl: 'cichy', en: 'quiet', note: '' },
        { group: 1, pl: 'zagubiony / stracony / zabłąkany', en: 'lost', note: '' },
        { group: 1, pl: 'przytłoczony', en: 'overwhelmed', note: '' },
        { group: 1, pl: 'surowy', en: 'raw', note: '' },
        { group: 1, pl: 'dziki (roslina , zwierzę)', en: 'wild', note: '' },
        { group: 1, pl: 'sprytny / cwaniacki', en: 'smart', note: '' },
        { group: 1, pl: 'pewien / pewny', en: 'sure', note: '' },
        { group: 1, pl: 'kolejny / następny', en: 'next', note: '' },
        { group: 1, pl: 'obowiązkowy / przymusowy', en: 'compulsory', note: '' },
        { group: 1, pl: 'chwilowy / przejściowy / tymczasowy', en: 'temporary', note: '' },
        { group: 1, pl: 'wybrany', en: 'chosen', note: '' },
        { group: 1, pl: 'widoczny / widzialny', en: 'visible', note: '' },
        { group: 1, pl: 'wylany (zwolniony z pracy)', en: 'fired', note: '' },
        { group: 1, pl: 'codzienny', en: 'everyday', note: '' },
        { group: 1, pl: 'każdy', en: 'every', note: '' },
        { group: 1, pl: 'jasny (pełny światła)', en: 'bright', note: '' },
        { group: 1, pl: 'najbliższ', en: 'nearest', note: '' },
    ],
];

export default adjectivesList;
