'use strict';
const adverbsList = [
    [
        {
            h1: 'PRZSŁÓWKI',
            table: {
                note1: 'ANGIELSKI',
                note2: '',
            },
            note: {},
        },
    ],
    [
        { group: 1, pl: 'mniej (np.: pieniędzy)', en: 'less', note: '' },
        { group: 1, pl: 'najmniej (np.: pieniędzy)', en: 'the least', note: '' },
        { group: 1, pl: 'tlko', en: 'only', note: '' },
        { group: 1, pl: 'tylko / zaledwie / ledwo', en: 'just', note: '' },
        { group: 1, pl: 'zdalnie', en: 'remotely', note: '' },
        { group: 1, pl: 'całkowicie / zupełnie / totalnie', en: 'totally', note: '' },
        { group: 1, pl: 'wcześnie (np.: wcześnie rano)', en: 'early', note: '' },
        { group: 1, pl: 'prawie / niemal / nieomal / mało co', en: 'almost', note: '' },
        { group: 1, pl: 'do siebie (np.: dodawać)', en: 'together', note: '' },
        { group: 1, pl: 'być może / może (możliwie)', en: 'perhaps', note: '' },
        { group: 1, pl: 'bardzo / nader', en: 'very', note: '' },
        { group: 1, pl: 'dużo / wiele', en: 'many', note: '' },
        { group: 1, pl: 'prawdopodobnie / zapewne', en: 'probably', note: '' },
        { group: 1, pl: 'blisko / niedaleko', en: 'near', note: '' },
        { group: 1, pl: 'strasznie / cholernie / mega', en: 'hella', note: '' },
        { group: 1, pl: 'najwięcej / najbardziej', en: 'the most', note: '' },
        { group: 1, pl: 'w dzisiejszych czasach / obecnie', en: 'nowadays', note: '' },
        { group: 1, pl: 'dobrze', en: 'well', note: '' },
        { group: 1, pl: 'nawet', en: 'even', note: '' },
        { group: 1, pl: 'jakby co / swoją drogą / przy okazji', en: 'by the way (BTW)', note: '' },
        { group: 1, pl: 'szybko', en: 'quickly  / fast', note: '' },
        { group: 1, pl: 'łatwo', en: 'easily', note: '' },
        { group: 1, pl: 'ciężko', en: 'hard', note: '' },
        { group: 1, pl: 'widocznie / wyraźnie', en: 'visibly', note: '' },
        { group: 1, pl: 'strasznie / straszliwie / okropnie', en: 'terribly', note: '' },
        { group: 1, pl: 'wolno / powoli / nieprędko', en: 'slowly', note: '' },
        { group: 1, pl: 'szczęśliwie / wesoło', en: 'happily', note: '' },
        { group: 1, pl: 'późno', en: 'late', note: '' },
        { group: 1, pl: 'zbyt', en: 'too', note: '' },
        { group: 1, pl: 'całkiem / dość / dośyć', en: 'quite', note: '' },
        { group: 1, pl: 'naprawdę  / bardzo', en: 'really', note: '' },
        { group: 1, pl: 'zwykle / zazwyczaj / na ogół', en: 'usually', note: '' },
        { group: 1, pl: 'często', en: 'often', note: '' },
        { group: 1, pl: 'nigdy', en: 'never', note: '' },
        { group: 1, pl: 'zawsze', en: 'always', note: '' },
        { group: 1, pl: 'teraz', en: 'now', note: '' },
        { group: 1, pl: 'jutro', en: 'tomorrow', note: '' },
        { group: 1, pl: 'dzisiaj', en: 'today', note: '' },
        { group: 1, pl: 'tutaj', en: 'here', note: '' },
        { group: 1, pl: 'tam', en: 'there', note: '' },
        { group: 1, pl: 'na zewnątrz / na dworze', en: 'outside', note: '' },
        { group: 1, pl: 'wewnątrz', en: 'inside', note: '' },
        { group: 1, pl: 'sam / sama', en: 'alone', note: '' },
        { group: 1, pl: 'osobiście', en: 'personally', note: '' },
        { group: 1, pl: 'generalnie / ogólnie /zwykle', en: 'generally', note: '' },
        { group: 1, pl: 'dziś wieczorem / dziś w nocy', en: 'tonight', note: '' },
        { group: 1, pl: 'całkowicie / kompletnie', en: 'absolutely', note: '' },
        { group: 1, pl: 'dokładnie tak / dokładnie (tak samo)', en: 'exactly', note: '' },
        { group: 1, pl: 'dokładnie recz biorąc', en: 'generally', note: '' },
        { group: 1, pl: 'trzymać', en: 'hold', note: '' },
        { group: 1, pl: 'wkrótce / niedługo', en: 'soon', note: '' },
    ],
];

export default adverbsList;
