'use strict';
const numberList = [
    [
        {
            h1: 'Liczby',
            table: {
                note1: 'ANGIELSKI',
                note2: '',
            },
            note: {},
        },
    ],
    [
        { group: 1, pl: 1, en: 'one', note: '' },
        { group: 1, pl: 2, en: 'two', note: '' },
        { group: 1, pl: 3, en: 'three', note: '' },
        { group: 1, pl: 4, en: 'four', note: '' },
        { group: 1, pl: 5, en: 'five', note: '' },
        { group: 1, pl: 6, en: 'six', note: '' },
        { group: 1, pl: 7, en: 'seven', note: '' },
        { group: 1, pl: 8, en: 'eight', note: '' },
        { group: 1, pl: 9, en: 'nine', note: '' },
        { group: 1, pl: 10, en: 'ten', note: '' },
        { group: 1, pl: 11, en: 'eleven', note: '' },
        { group: 1, pl: 12, en: 'twelve', note: '' },
        { group: 1, pl: 13, en: 'thirteen', note: '' },
        { group: 1, pl: 14, en: 'fourteen', note: '' },
        { group: 1, pl: 15, en: 'fifteen', note: '' },
        { group: 1, pl: 16, en: 'sixten', note: '' },
        { group: 1, pl: 17, en: 'seventeen', note: '' },
        { group: 1, pl: 18, en: 'eighten', note: '' },
        { group: 1, pl: 19, en: 'nineteen', note: '' },
        { group: 1, pl: 20, en: 'twenty', note: '' },
        { group: 1, pl: 21, en: 'twenty-one', note: '' },
        { group: 1, pl: 22, en: 'twenty-two', note: '' },
        { group: 1, pl: 23, en: 'twenty-three', note: '' },
        { group: 1, pl: 24, en: 'twenty-four', note: '' },
        { group: 1, pl: 25, en: 'twenty-five', note: '' },
        { group: 1, pl: 26, en: 'twenty-six', note: '' },
        { group: 1, pl: 27, en: 'twenty-seven', note: '' },
        { group: 1, pl: 28, en: 'twenty-eight', note: '' },
        { group: 1, pl: 29, en: 'twenty-nine', note: '' },
        { group: 1, pl: 30, en: 'thirty', note: '' },
        { group: 1, pl: 31, en: 'thirty-one', note: '' },
        { group: 1, pl: 40, en: 'forty', note: '' },
        { group: 1, pl: 50, en: 'fifty', note: '' },
        { group: 1, pl: 60, en: 'sixty', note: '' },
        { group: 1, pl: 70, en: 'seventy', note: '' },
        { group: 1, pl: 80, en: 'eighty', note: '' },
        { group: 1, pl: 90, en: 'ninty', note: '' },
        { group: 1, pl: 100, en: 'one hubdret', note: '' },
        { group: 1, pl: 1000, en: 'one thousand', note: '' },
        { group: 1, pl: 1000000, en: 'one milion', note: '' },
    ],
];

export default numberList;
