'use strict';
const phrasalVerbsList = [
    [
        {
            h1: 'CZASOWNIKI FRAZALNE',
            table: {
                note1: 'FRAZAL',
                note2: 'BEZOKOLICZNIK',
            },
            note: {},
        },
    ],

    [
        { irregular: false, pl: 'opiekować się . troszczyć', en: 'care for', note: 'care' },
        { irregular: false, pl: 'zepsuć się', en: 'break down', note: 'break' },
        { irregular: false, pl: 'dorastać', en: 'grow up', note: 'grow' },
        { irregular: false, pl: 'mieć zamiar', en: 'be about to', note: 'be' },
        { irregular: false, pl: 'zgadzać się', en: 'be for', note: 'be' },
        { irregular: false, pl: 'być nieobecnym / wyłączyć się', en: 'be off', note: 'be' },
        { irregular: false, pl: 'być (obecnie) włączonym', en: 'be on', note: 'be' },
        { irregular: false, pl: 'zgasnąć / być poza domem / wyjść z mody', en: 'be out', note: 'be' },
        { irregular: false, pl: 'zajmować się (czymś)', en: 'be up to', note: 'be' },
        { irregular: false, pl: 'zakończyć się', en: 'be over', note: 'be' },
        { irregular: false, pl: 'napotkac / spotkać / natknąć się', en: 'come across', note: 'come' },
        { irregular: false, pl: 'stać się / zdarzyć się', en: 'come about', note: 'come' },
        { irregular: false, pl: 'uspokuj się / obnirzać się / zejść', en: 'come down', note: 'come' },
        { irregular: false, pl: 'wchodzić / wejść do / odziedziczyć', en: 'come into', note: 'come' },
        { irregular: false, pl: 'puść / oderwać się / odpaść', en: 'come off', note: 'come' },
        { irregular: false, pl: 'wyjść / wychodzić', en: 'come out', note: 'come' },
        { irregular: false, pl: 'dojść do siebie', en: 'come round', note: 'come' },
        { irregular: false, pl: 'warcać', en: 'come back', note: 'come' },
        { irregular: false, pl: 'przyjść do', en: 'come to', note: 'come' },
        { irregular: false, pl: 'pojawić się', en: 'come up', note: 'come' },
        { irregular: false, pl: 'przyjść do', en: 'come up to', note: 'come' },
        { irregular: false, pl: 'sprawdzać', en: 'check out', note: 'check' },
        { irregular: false, pl: 'posprzątać', en: 'clean up', note: 'clean' },
        { irregular: false, pl: 'przejaśnieć się', en: 'clear up', note: 'clear' },
        { irregular: false, pl: 'rozlecieć się', en: 'fall apart', note: 'fall' },
        { irregular: false, pl: 'wrócić / zawrócić', en: 'fall back', note: 'fall' },
        { irregular: false, pl: 'uciec się do', en: 'fall back on', note: 'fall' },
        { irregular: false, pl: 'odstawać / obsuwć się', en: 'fall behind', note: 'fall' },
        { irregular: false, pl: 'zmniejszać się / spaść', en: 'fall down', note: 'fall' },
        { irregular: false, pl: 'zakochać się / dać się nabrać', en: 'fall for', note: 'fall' },
        { irregular: false, pl: 'odpaść', en: 'fall off', note: 'fall' },
        { irregular: false, pl: 'kłócić się z', en: 'fall out with', note: 'fall' },
        { irregular: false, pl: 'nie udać się', en: 'fall through', note: 'fall' },
        { irregular: false, pl: 'oddać / zwrócić', en: 'give back', note: 'give' },
        { irregular: false, pl: 'poddać się', en: 'give in', note: 'give' },
        { irregular: false, pl: 'wycielać coś / ogłosić coć', en: 'give ogg', note: 'give' },
        { irregular: false, pl: 'prowadzić do', en: 'give one to', note: 'give' },
        { irregular: false, pl: 'pskończyć się / wydawać', en: 'give out', note: 'give' },
        { irregular: false, pl: 'okrążyć / obiec', en: 'go around', note: 'go' },
        { irregular: false, pl: 'wrócić', en: 'go back', note: 'go' },
        { irregular: false, pl: 'zostać przyjętym / odebranym', en: 'go down', note: 'go' },
        { irregular: false, pl: 'wziąć udział', en: 'go in', note: 'go' },
        { irregular: false, pl: 'badać / przyglądać się czemuś', en: 'go into', note: 'go' },
        { irregular: false, pl: 'wybuchnąć / odejść', en: 'go off', note: 'go' },
        { irregular: false, pl: 'kontynułować', en: 'go on', note: 'go' },
        { irregular: false, pl: 'sprawdzić', en: 'go over', note: 'go' },
        { irregular: false, pl: 'podjąć trud / udać się do', en: 'go to', note: 'go' },
        { irregular: false, pl: 'wzrastać / być stawianym (np.: budynek)', en: 'go up', note: 'go' },
    ],
];
export default phrasalVerbsList;
