'use strict';
const verbsList = [
  [{
    h1: 'CZASOWNIKI',
    table: {
      note1: 'BEZOKOLICZNIK',
      note2: 'PAST SIMPLE',
    },
    note: {},
  }, ],
  [
    { irregular: true, pl: 'wykonać / robić', en: 'make', note: 'made' },
    { irregular: true, pl: 'czytać', en: 'read', note: 'read' },
    { irregular: true, pl: 'dzwonić', en: 'ring', note: 'rang' },
    { irregular: true, pl: 'siedzieć / siadać', en: 'sit', note: 'sat' },
    { irregular: true, pl: 'mówić', en: 'speak', note: 'spoke' },
    { irregular: true, pl: 'stać', en: 'stand', note: 'stood' },
    { irregular: true, pl: 'brać / robić', en: 'take', note: 'took' },
    { irregular: true, pl: 'budzić się', en: 'wake', note: 'woke' },
    { irregular: true, pl: 'pisać', en: 'write', note: 'wrote' },
    { irregular: true, pl: 'zapalać', en: 'light', note: 'lit' },
    { irregular: true, pl: 'wycofać', en: 'withdraw', note: 'withdrew' },
    { irregular: true, pl: 'rozpoczynać', en: 'begin', note: 'began' },
    { irregular: true, pl: 'rosnąć', en: 'grow', note: 'grew' },
    { irregular: true, pl: 'prowadzić / przewodzić', en: 'lead', note: 'led' },
    { irregular: true, pl: 'przychodzić', en: 'come', note: 'came' },
    { irregular: true, pl: 'obciąć / skaleczyć się', en: 'cut', note: 'cut' },
    { irregular: true, pl: 'rysować', en: 'draw', note: 'drew' },
    { irregular: true, pl: 'dostać', en: 'get', note: 'got' },
    { irregular: true, pl: 'ukryć / shować się', en: 'hide', note: 'hid' },
    { irregular: true, pl: 'trzymać / mieścić', en: 'hold', note: 'held' },
    { irregular: true, pl: 'wkładać / kłaść', en: 'put', note: 'put' },
    { irregular: true, pl: 'usatwić / ustalać', en: 'set', note: 'set' },
    { irregular: true, pl: 'nosić / mieć na sobie / być ubranym', en: 'wear', note: 'wore' },
    { irregular: true, pl: 'latać', en: 'fly', note: 'flew' },
    { irregular: true, pl: 'iść', en: 'go', note: 'went' },
    { irregular: true, pl: 'wyjść / wychodzić / wyjeżdżać', en: 'leave', note: 'left' },
    { irregular: true, pl: 'jeździć', en: 'ride', note: 'rode' },
    { irregular: true, pl: 'wysyłać', en: 'send', note: 'sent' },
    { irregular: true, pl: 'wschodzić', en: 'rise', note: 'rose' },
    { irregular: true, pl: 'pływać', en: 'swim', note: 'swam' },
    { irregular: true, pl: 'dmuchać / wiać', en: 'blow', note: 'blew' },
    { irregular: true, pl: 'budować', en: 'build', note: 'built' },
    { irregular: true, pl: 'świecić się / błyszcześ', en: 'shine', note: 'shone' },
    { irregular: true, pl: 'kupować', en: 'buy', note: 'bought' },
    { irregular: true, pl: 'uczyć się', en: 'learn', note: 'learnt' },
    { irregular: true, pl: 'płacić', en: 'pay', note: 'paid' },
    { irregular: true, pl: 'sprzedać', en: 'sell', note: 'sold' },
    { irregular: true, pl: 'spędzać', en: 'spend', note: 'spent' },
    { irregular: true, pl: 'śnić / marzyć', en: 'dream', note: 'taught' },
    { irregular: true, pl: 'słyszeć', en: 'hear', note: 'heard' },
    { irregular: true, pl: 'wiedzieć / znać', en: 'know', note: 'knew' },
    { irregular: true, pl: 'widzieć', en: 'see', note: 'saw' },
    { irregular: true, pl: 'myśleć', en: 'think', note: 'thought' },
    { irregular: true, pl: 'rozumieć', en: 'understand', note: 'understood' },
    { irregular: true, pl: 'karmić', en: 'feed', note: 'fed' },
    { irregular: true, pl: 'czuć', en: 'feel', note: 'felt' },
    { irregular: true, pl: 'śpiewać', en: 'sing', note: 'sen' },
    { irregular: true, pl: 'pachnieć / wąchać', en: 'smell', note: 'smelt' },
    { irregular: true, pl: 'kraść', en: 'steal', note: 'stole' },
    { irregular: true, pl: 'palić / parzyć', en: 'burn', note: 'burnt' },
    { irregular: true, pl: 'walczyć', en: 'fight', note: 'fought' },
    { irregular: true, pl: 'wieszać', en: 'hen', note: 'hung' },
    { irregular: true, pl: 'uderzyć / trafić', en: 'hit', note: 'hit' },
    { irregular: true, pl: 'ranić', en: 'hurt', note: 'hurt' },
    { irregular: true, pl: 'bić', en: 'beat', note: 'beat' },
    { irregular: true, pl: 'wygrywać', en: 'win', note: 'won' },
    { irregular: true, pl: 'gryźć', en: 'bite', note: 'bit' },
    { irregular: true, pl: 'wstrząsnąć', en: 'shake', note: 'shook' },
    { irregular: true, pl: 'strzelać', en: 'shoot', note: 'shot' },
    { irregular: true, pl: 'tonąć', en: 'sink', note: 'sank' },
    { irregular: true, pl: 'podrzeć', en: 'tear', note: 'tore' },
    { irregular: true, pl: 'rzucać', en: 'throw', note: 'threw' },
    { irregular: true, pl: 'złamać / zepsuć', en: 'break', note: 'broke' },
    { irregular: true, pl: 'łapać', en: 'catch', note: 'caught' },
    { irregular: true, pl: 'spadać / upaść', en: 'fall', note: 'fell' },
    { irregular: true, pl: 'dawać', en: 'give', note: 'gave' },
    { irregular: true, pl: 'zgubić / przegrać', en: 'lose', note: 'lost' },
    { irregular: true, pl: 'powiedzieć', en: 'tell', note: 'told' },
    { irregular: true, pl: 'wybaczać', en: 'forgive', note: 'forgave' },
    { irregular: true, pl: 'pozwolić / pozwalać', en: 'let', note: 'let' },
    { irregular: true, pl: 'znaczyć / mieć na myśli', en: 'mean', note: 'meant' },
    { irregular: true, pl: 'nie spać', en: 'awake', note: 'awoke' },
    { irregular: true, pl: 'pokazywać', en: 'show', note: 'showed' },
    { irregular: true, pl: 'pożyczać (coś komuś)', en: 'lend', note: 'lent' },
    { irregular: true, pl: 'przynosić', en: 'bring', note: 'brought' },
    { irregular: true, pl: 'móc / mogę / potrafię', en: 'can', note: 'could' },
    { irregular: true, pl: 'wybierać', en: 'choose', note: 'chose' },
    { irregular: true, pl: 'robić / wykonywać', en: 'do', note: 'did' },
    { irregular: true, pl: 'pić', en: 'drink', note: 'drank' },
    { irregular: true, pl: 'jeść', en: 'eat', note: 'ate' },
    { irregular: true, pl: 'znalesć', en: 'find', note: 'fond' },
    { irregular: true, pl: 'zapomnieć', en: 'forget', note: 'forgot' },
    { irregular: true, pl: 'mieć', en: 'have', note: 'had' },
    { irregular: true, pl: 'kłaść / położyć', en: 'lay', note: 'laid' },
    { irregular: true, pl: 'leżeć', en: 'lie', note: 'lay' },
    { irregular: true, pl: 'stać się / zostać / zostawać (kimś)', en: 'become', note: 'become<u>d</u>' },
    { irregular: true, pl: 'trzymać / zostawić / hodować', en: 'keep', note: 'kept' },
    { irregular: false, pl: 'pytać', en: 'ask', note: 'asked' },
    { irregular: false, pl: 'odpowiadać', en: 'answer', note: 'answer<u>ed</u>' },
    { irregular: false, pl: 'powinien / powinno się', en: 'should', note: 'should<u>ed</u>' },
    { irregular: false, pl: 'patrzeć', en: 'look', note: 'look<u>ed</u>' },
    { irregular: true, pl: 'powiedzieć / mówić', en: 'say', note: 'said' },
    { irregular: false, pl: 'ufać / wierzyć', en: 'trust', note: 'trust<u>ed</u>' },
    { irregular: false, pl: 'pracować / działać', en: 'work', note: 'work<u>ed</u>' },
    { irregular: false, pl: 'dzwonić / nazywać', en: 'call', note: 'call<u>ed</u>' },
    { irregular: false, pl: 'próbować / starać się', en: 'try', note: 'tr<u>ied</u>' },
    { irregular: false, pl: 'potrzebować', en: 'need', note: 'need<u>ed</u>' },
    { irregular: false, pl: 'preferować / woleć', en: 'prefer', note: 'prefer<u>red</u>' },
    { irregular: false, pl: 'zezwalać na / pozwalać', en: 'allow', note: 'allow<u>ed</u>' },
    { irregular: false, pl: 'wydawać się', en: 'seem', note: 'seem<u>ed</u>' },
    { irregular: false, pl: 'pomagać / wspierać', en: 'help', note: 'help<u>ed</u>' },
    { irregular: false, pl: 'grać / odtwarzać / bawić się', en: 'play', note: 'pla<u>ied</u>' },
    { irregular: true, pl: 'biegać', en: 'run', note: 'ran' },
    { irregular: false, pl: 'mieszkać / żyć', en: 'live', note: 'liv<u>ed</u>' },
    { irregular: false, pl: 'ruszać (się) / przenosić (się)', en: 'move', note: 'move<u>d</u>' },
    { irregular: false, pl: 'rozmawiać', en: 'talk', note: 'talk<u>ed</u> ' },
    { irregular: false, pl: 'chcieć', en: 'want', note: 'want<u>ed</u> ' },
    { irregular: false, pl: 'uruchamiać / wystrzelić / odpalić', en: 'launch', note: 'launch<u>ed</u>' },
    { irregular: false, pl: 'zaproszać', en: 'invite', note: 'invit<u>ed</u>' },
    { irregular: false, pl: 'kwitnąć', en: 'blossom', note: 'blossom<u>ed</u>' },
    { irregular: false, pl: 'dostarczyć', en: 'deliver', note: 'deliver<u>ed</u>' },
    { irregular: false, pl: 'przerywać / przeszkadzać', en: 'interrupt', note: 'interrupt<u>ed</u>' },
    { irregular: true, pl: 'spotykać / poznawać', en: 'meet', note: 'met' },
    { irregular: true, pl: 'zakazać / zabraniać', en: 'forbid', note: 'forbade' },
    { irregular: false, pl: 'dwracać się / skręcać / obracać', en: 'turn', note: 'turn<u>ed</u>' },
    { irregular: false, pl: 'zamierzać', en: 'going to', note: 'gonna' },
    { irregular: false, pl: 'musieć', en: 'have go to', note: 'gotta' },
    { irregular: true, pl: 'opuścić / porzucić', en: 'forsake', note: 'forsook' },
    { irregular: false, pl: 'nienawidzić', en: 'hate', note: 'hate<u>d</u>' },
    { irregular: false, pl: 'podziwiać / szanować', en: 'admire', note: 'admire<u>d</u>' },
    { irregular: false, pl: 'poprawić (się) / ulepszyć', en: 'improve', note: ' improve<u>d</u>' },
    { irregular: false, pl: 'przybywać / przyjechać / przylatywać', en: 'arrive', note: 'arrive<u>d</u>' },
    { irregular: false, pl: 'przypuszczać / zakładać', en: 'assume', note: 'assume<u>d</u>' },
    { irregular: false, pl: 'mieć swoje miejsce / prznależeć / należeć', en: 'belong', note: 'belong<u>ed</u>' },
    { irregular: false, pl: 'doceniać / rozumieć', en: 'appreciate', note: 'appreciate<u>d</u>' },
    { irregular: false, pl: 'zgadzać się / podzielać opinię', en: 'agree', note: 'agree<u>d</u>' },
    { irregular: false, pl: 'zależeć (być uzależnionym)', en: 'depend', note: 'depende<u>d</u>' },
    { irregular: false, pl: 'martwić się', en: 'worry', note: 'worr<u>ied</u>' },
    { irregular: false, pl: 'dotyczyć / niepokoić', en: 'concern', note: 'concerne<u>d</u>' },
    { irregular: false, pl: 'boleć', en: 'ache', note: 'ache<u>d</u>' },
    { irregular: false, pl: 'nosić / dźwigać', en: 'carry', note: 'carr<u>ied</u>' },
    { irregular: false, pl: 'smak', en: 'taste', note: 'taste<u>d</u>' },
    { irregular: false, pl: 'uwielbiać', en: 'adore', note: 'adore<u>d</u>' },
    { irregular: false, pl: 'przekroczyć (limit) / przewyższyć', en: 'exceed', note: 'exceed<u>ed</u>' },
    { irregular: true, pl: 'rzucać', en: 'quit', note: 'quitted' },
    { irregular: false, pl: 'lubić', en: 'like', note: 'like<u>d</u>' },
    { irregular: false, pl: 'gwarantować', en: 'guarantee', note: '' },
    { irregular: false, pl: 'aprobować / zatwierdzać / akceptować', en: 'approve', note: 'approve<u>d</u>' },
    { irregular: false, pl: 'słuchać', en: 'listen', note: 'listen<u>ed</u>' },
    { irregular: false, pl: 'dodawać', en: 'add', note: 'add<u>ed</u>' },
    { irregular: false, pl: 'lubić / czerpać przyjemnosć', en: 'enjoy', note: 'enjoy<u>ed</u>' },
    { irregular: false, pl: 'roztapiać / topić', en: 'melt', note: 'melt<u>ed</u>' },
    { irregular: false, pl: 'pożyczać (coś od kogoś)', en: 'borrow', note: 'borrow<u>ed</u>' },
    { irregular: false, pl: 'chronić / zabezpieczyć / nronić', en: 'protect', note: 'protect<u>ed</u>' },
    { irregular: false, pl: 'chichotać', en: 'giggle', note: 'giggle<u>d</u>' },
    { irregular: false, pl: 'mieć na coś pieniądze', en: 'afford', note: 'afford<u>ed</u>' },
    { irregular: false, pl: 'śmiać się', en: 'laugh', note: 'laugh<u>ed</u>' },
    { irregular: false, pl: 'aktualizować', en: 'update', note: 'update<u>d</u>' },
    { irregular: false, pl: 'unosić się', en: 'float', note: 'float<u>ed</u>' },
    { irregular: false, pl: 'nie zgadzać się', en: 'disagree', note: 'disagre<u>d</u>' },
    { irregular: false, pl: 'spacerować / chodzić', en: 'walk', note: 'walk<u>ed</u>' },
    { irregular: true, pl: 'spać', en: 'sleep', note: 'slept' },
    { irregular: false, pl: 'płakać', en: 'cry', note: 'cr<u>ied</u>' },
    { irregular: false, pl: 'odkurzać', en: 'vacuum', note: '' },
    { irregular: false, pl: 'pamiętać', en: 'remember', note: 'remember<u>ed</u>' },
    { irregular: false, pl: 'prasować', en: 'iron', note: 'iron<u>ed</u>' },
    { irregular: false, pl: 'zarabiać (pieniądze)', en: 'earn', note: 'earn<u>ed</u>' },
    { irregular: true, pl: 'zamiatać', en: 'sweep', note: 'sweept' },
    { irregular: true, pl: 'wejść', en: 'get in', note: 'got in' },
    { irregular: true, pl: 'wyjść / wyjeżdżać', en: 'get out', note: 'got out' },
    { irregular: false, pl: 'wejść', en: 'enter', note: 'enter<u>ed</u>' },
    { irregular: false, pl: 'zamykać', en: 'lock', note: 'lock<u>ed</u>' },
    { irregular: false, pl: 'wynaleźć', en: 'invent', note: 'invent<u>ed</u>' },
    { irregular: false, pl: 'wydarzyć się / zdarzyć', en: 'happen', note: 'happen<u>ed</u>' },
    { irregular: false, pl: 'przygotowywać', en: 'prepare', note: 'prepare<u>ed</u>' },
    { irregular: false, pl: 'zauważyć', en: 'notice', note: 'notice<u>d</u>' },
    { irregular: false, pl: 'integrować / wprowadzać', en: 'integrate', note: 'integrate<u>d</u>' },
    { irregular: false, pl: 'doszkalać / podniesć kwalifikacje', en: 'upskill', note: 'upskill<u>ed</u>' },
    { irregular: false, pl: 'przystosowywać się / dostosowywać się', en: 'adapt', note: 'adapt<u>ed</u>' },
    { irregular: false, pl: 'osądzać / sądzić', en: 'judge', note: '' },
    { irregular: false, pl: 'order', en: 'zamawiać', note: '' },
    { irregular: false, pl: 'popełniać / dopuszczać się', en: 'commit', note: 'commit<u>ed</u>' },
    { irregular: false, pl: 'zrywać / zbierać', en: 'pick', note: 'pick<u>ed</u>' },
    { irregular: false, pl: 'eksponować / odsłaniać', en: 'expose', note: 'expos<u>ed</u>' },
    { irregular: false, pl: 'zrywać', en: 'pick', note: 'pick<u>ed</u>' },
    { irregular: false, pl: 'zgadywać / domyślać się', en: 'guess', note: 'guess<u>ed</u>' },
    { irregular: false, pl: 'przypuszczać', en: 'suppose', note: 'suppos<u>ed</u>' },
    { irregular: false, pl: 'oczekiwać / spodziwać się / spodziewać się', en: 'expect', note: 'expect<u>ed</u>' },
    { irregular: false, pl: 'wierzyć / uwierzyć', en: 'believe', note: '?' },
    { irregular: false, pl: 'robić porządki / sprzątać', en: 'tidy up', note: '?' },
    { irregular: false, pl: 'podróżować', en: 'travel', note: 'travel<u>ed</u>' },
    { irregular: false, pl: 'przeprowadzać się / przenieść / ruszaj się', en: 'move', note: 'mov<u>ed</u>' },
    { irregular: false, pl: 'studiować', en: 'study', note: 'study<u>ed</u>' },
    { irregular: false, pl: 'włączać / wliczać / zawierać', en: 'include', note: 'includ<u>ed</u>' },
    { irregular: false, pl: 'zawachać się / wahać się', en: 'hesitate', note: 'hesitat<u>ed</u>' },
    { irregular: false, pl: 'przedstawić / zapoznawać', en: 'introduce', note: 'introduc<u>ed</u>' },
    { irregular: false, pl: 'przesunąć', en: 'swipe', note: 'swip<u>ed</u>' },
    { irregular: false, pl: 'dezaktywować / wyłączyć', en: 'deactivate', note: 'deactivat<u>ed</u>' },
    { irregular: false, pl: 'wyglądać', en: 'look', note: 'look<u>ed</u>' },
    { irregular: false, pl: 'rzuć monetą', en: 'toss a coin', note: '' },
    { irregular: false, pl: 'zawinąć / owinąć / zapakować', en: 'wrap', note: 'wrap<u>ed</u>' },
    { irregular: false, pl: 'porównywać', en: 'compare', note: 'compar<u>ed</u>' },
    { irregular: false, pl: 'transmitować / nadawać', en: 'broadcast', note: '' },
    { irregular: false, pl: 'kopać', en: 'dig', note: 'dig<u>ed</u>' },
    { irregular: false, pl: 'chwiać się / chybotać się / kiwać się', en: 'wobble', note: 'wobbl<u>ed</u>' },
    { irregular: false, pl: 'ziewać', en: 'yawn', note: 'yawn<u>ed</u>' },
    { irregular: false, pl: 'zaspać', en: 'ovrsleep', note: 'oversleep<u>ed</u>' },
  ],
];

export default verbsList;